# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='requests.proto',
  package='pairing_server',
  syntax='proto3',
  serialized_pb=_b('\n\x0erequests.proto\x12\x0epairing_server\x1a\x0btypes.proto\"\xb9\x03\n\x07Request\x12.\n\ntournament\x18\x01 \x01(\x0b\x32\x1a.pairing_server.Tournament\x12\x30\n\x06player\x18\x02 \x01(\x0b\x32 .pairing_server.TournamentPlayer\x12,\n\x04game\x18\x03 \x01(\x0b\x32\x1e.pairing_server.TournamentGame\x12\x34\n\toperation\x18\x04 \x01(\x0e\x32!.pairing_server.Request.Operation\"\xe7\x01\n\tOperation\x12\x08\n\x04PING\x10\x00\x12\x15\n\x11TOURNAMENT_CREATE\x10\x01\x12\x12\n\x0eTOURNAMENT_GET\x10\x02\x12\x13\n\x0fTOURNAMENT_EDIT\x10\x03\x12\x11\n\rPLAYER_SIGNUP\x10\x04\x12\x0e\n\nPLAYER_GET\x10\x05\x12\x0f\n\x0bPLAYER_EDIT\x10\x06\x12\x0c\n\x08GAME_GET\x10\x07\x12\x18\n\x14GAME_REGISTER_RESULT\x10\x08\x12\x18\n\x14TOURNAMENT_GET_ROUND\x10\t\x12\x1a\n\x16TOURNAMENT_GET_PLAYERS\x10\n\"\xa0\x03\n\x08Response\x12/\n\x06status\x18\x01 \x01(\x0e\x32\x1f.pairing_server.Response.Status\x12/\n\x0btournaments\x18\x02 \x03(\x0b\x32\x1a.pairing_server.Tournament\x12\x31\n\x07players\x18\x03 \x03(\x0b\x32 .pairing_server.TournamentPlayer\x12-\n\x05games\x18\x04 \x03(\x0b\x32\x1e.pairing_server.TournamentGame\x12\x30\n\x07reasons\x18\x05 \x03(\x0e\x32\x1f.pairing_server.Response.Reason\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"\x80\x01\n\x06Reason\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x12\n\x0eINTERNAL_ERROR\x10\x01\x12\x10\n\x0cMISSING_HMAC\x10\x02\x12\x0e\n\nWRONG_HMAC\x10\x03\x12\x10\n\x0cMISSING_UUID\x10\x04\x12\r\n\tNOT_FOUND\x10\x05\x12\x0e\n\nINCOMPLETE\x10\x06\x62\x06proto3')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_REQUEST_OPERATION = _descriptor.EnumDescriptor(
  name='Operation',
  full_name='pairing_server.Request.Operation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOURNAMENT_CREATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOURNAMENT_GET', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOURNAMENT_EDIT', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_SIGNUP', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_GET', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYER_EDIT', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_GET', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GAME_REGISTER_RESULT', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOURNAMENT_GET_ROUND', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOURNAMENT_GET_PLAYERS', index=10, number=10,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=258,
  serialized_end=489,
)
_sym_db.RegisterEnumDescriptor(_REQUEST_OPERATION)

_RESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='pairing_server.Response.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=750,
  serialized_end=777,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_STATUS)

_RESPONSE_REASON = _descriptor.EnumDescriptor(
  name='Reason',
  full_name='pairing_server.Response.Reason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_ERROR', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_HMAC', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRONG_HMAC', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MISSING_UUID', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCOMPLETE', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=780,
  serialized_end=908,
)
_sym_db.RegisterEnumDescriptor(_RESPONSE_REASON)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='pairing_server.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tournament', full_name='pairing_server.Request.tournament', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player', full_name='pairing_server.Request.player', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='game', full_name='pairing_server.Request.game', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operation', full_name='pairing_server.Request.operation', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REQUEST_OPERATION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=489,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='pairing_server.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='pairing_server.Response.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tournaments', full_name='pairing_server.Response.tournaments', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='players', full_name='pairing_server.Response.players', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='games', full_name='pairing_server.Response.games', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reasons', full_name='pairing_server.Response.reasons', index=4,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSE_STATUS,
    _RESPONSE_REASON,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=908,
)

_REQUEST.fields_by_name['tournament'].message_type = types__pb2._TOURNAMENT
_REQUEST.fields_by_name['player'].message_type = types__pb2._TOURNAMENTPLAYER
_REQUEST.fields_by_name['game'].message_type = types__pb2._TOURNAMENTGAME
_REQUEST.fields_by_name['operation'].enum_type = _REQUEST_OPERATION
_REQUEST_OPERATION.containing_type = _REQUEST
_RESPONSE.fields_by_name['status'].enum_type = _RESPONSE_STATUS
_RESPONSE.fields_by_name['tournaments'].message_type = types__pb2._TOURNAMENT
_RESPONSE.fields_by_name['players'].message_type = types__pb2._TOURNAMENTPLAYER
_RESPONSE.fields_by_name['games'].message_type = types__pb2._TOURNAMENTGAME
_RESPONSE.fields_by_name['reasons'].enum_type = _RESPONSE_REASON
_RESPONSE_STATUS.containing_type = _RESPONSE
_RESPONSE_REASON.containing_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'requests_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
