# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types.proto',
  package='pairing_server',
  syntax='proto3',
  serialized_pb=_b('\n\x0btypes.proto\x12\x0epairing_server\"F\n\nTournament\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06rounds\x18\x02 \x01(\r\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x0c\n\x04hmac\x18\x04 \x01(\t\"|\n\x10TournamentPlayer\x12\x0c\n\x04name\x18\x01 \x01(\t\x12.\n\ntournament\x18\x02 \x01(\x0b\x32\x1a.pairing_server.Tournament\x12\x0e\n\x06rating\x18\x03 \x01(\r\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\x0c\n\x04hmac\x18\x05 \x01(\t\"\xb6\x02\n\x0eTournamentGame\x12\r\n\x05round\x18\x01 \x01(\r\x12/\n\x05white\x18\x02 \x01(\x0b\x32 .pairing_server.TournamentPlayer\x12/\n\x05\x62lack\x18\x03 \x01(\x0b\x32 .pairing_server.TournamentPlayer\x12\x35\n\x06result\x18\x04 \x01(\x0e\x32%.pairing_server.TournamentGame.Result\x12\x0c\n\x04uuid\x18\x05 \x01(\t\x12\x0c\n\x04hmac\x18\x06 \x01(\t\"`\n\x06Result\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x44RAW\x10\x01\x12\r\n\tWHITE_WIN\x10\x02\x12\r\n\tBLACK_WIN\x10\x03\x12\x11\n\rWHITE_FORFEIT\x10\x04\x12\x11\n\rBLACK_FORFEIT\x10\x05\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_TOURNAMENTGAME_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pairing_server.TournamentGame.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_WIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK_WIN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_FORFEIT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK_FORFEIT', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=444,
  serialized_end=540,
)
_sym_db.RegisterEnumDescriptor(_TOURNAMENTGAME_RESULT)


_TOURNAMENT = _descriptor.Descriptor(
  name='Tournament',
  full_name='pairing_server.Tournament',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pairing_server.Tournament.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rounds', full_name='pairing_server.Tournament.rounds', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='pairing_server.Tournament.uuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hmac', full_name='pairing_server.Tournament.hmac', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=101,
)


_TOURNAMENTPLAYER = _descriptor.Descriptor(
  name='TournamentPlayer',
  full_name='pairing_server.TournamentPlayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='pairing_server.TournamentPlayer.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tournament', full_name='pairing_server.TournamentPlayer.tournament', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rating', full_name='pairing_server.TournamentPlayer.rating', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='pairing_server.TournamentPlayer.uuid', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hmac', full_name='pairing_server.TournamentPlayer.hmac', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=227,
)


_TOURNAMENTGAME = _descriptor.Descriptor(
  name='TournamentGame',
  full_name='pairing_server.TournamentGame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='round', full_name='pairing_server.TournamentGame.round', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='white', full_name='pairing_server.TournamentGame.white', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='black', full_name='pairing_server.TournamentGame.black', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='pairing_server.TournamentGame.result', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='pairing_server.TournamentGame.uuid', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hmac', full_name='pairing_server.TournamentGame.hmac', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TOURNAMENTGAME_RESULT,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=540,
)

_TOURNAMENTPLAYER.fields_by_name['tournament'].message_type = _TOURNAMENT
_TOURNAMENTGAME.fields_by_name['white'].message_type = _TOURNAMENTPLAYER
_TOURNAMENTGAME.fields_by_name['black'].message_type = _TOURNAMENTPLAYER
_TOURNAMENTGAME.fields_by_name['result'].enum_type = _TOURNAMENTGAME_RESULT
_TOURNAMENTGAME_RESULT.containing_type = _TOURNAMENTGAME
DESCRIPTOR.message_types_by_name['Tournament'] = _TOURNAMENT
DESCRIPTOR.message_types_by_name['TournamentPlayer'] = _TOURNAMENTPLAYER
DESCRIPTOR.message_types_by_name['TournamentGame'] = _TOURNAMENTGAME

Tournament = _reflection.GeneratedProtocolMessageType('Tournament', (_message.Message,), dict(
  DESCRIPTOR = _TOURNAMENT,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Tournament)
  ))
_sym_db.RegisterMessage(Tournament)

TournamentPlayer = _reflection.GeneratedProtocolMessageType('TournamentPlayer', (_message.Message,), dict(
  DESCRIPTOR = _TOURNAMENTPLAYER,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.TournamentPlayer)
  ))
_sym_db.RegisterMessage(TournamentPlayer)

TournamentGame = _reflection.GeneratedProtocolMessageType('TournamentGame', (_message.Message,), dict(
  DESCRIPTOR = _TOURNAMENTGAME,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.TournamentGame)
  ))
_sym_db.RegisterMessage(TournamentGame)


# @@protoc_insertion_point(module_scope)
