# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: types.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='types.proto',
  package='pairing_server',
  syntax='proto3',
  serialized_pb=_b('\n\x0btypes.proto\x12\x0epairing_server\")\n\x04Hmac\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\x0c\"B\n\x0eIdentification\x12\x0c\n\x04uuid\x18\x01 \x01(\x0c\x12\"\n\x04hmac\x18\x02 \x01(\x0b\x32\x14.pairing_server.Hmac\"V\n\nTournament\x12*\n\x02id\x18\x01 \x01(\x0b\x32\x1e.pairing_server.Identification\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06rounds\x18\x03 \x01(\r\"\xa7\x01\n\x06Player\x12*\n\x02id\x18\x01 \x01(\x0b\x32\x1e.pairing_server.Identification\x12\x0c\n\x04name\x18\x02 \x01(\t\x12.\n\ntournament\x18\x03 \x01(\x0b\x32\x1a.pairing_server.Tournament\x12\x0e\n\x06rating\x18\x04 \x01(\r\x12\x11\n\twithdrawn\x18\x05 \x01(\x08\x12\x10\n\x08\x65xpelled\x18\x06 \x01(\x08\"\xe7\x01\n\x04Game\x12*\n\x02id\x18\x01 \x01(\x0b\x32\x1e.pairing_server.Identification\x12.\n\ntournament\x18\x02 \x01(\x0b\x32\x1a.pairing_server.Tournament\x12\r\n\x05round\x18\x03 \x01(\r\x12%\n\x05white\x18\x04 \x01(\x0b\x32\x16.pairing_server.Player\x12%\n\x05\x62lack\x18\x05 \x01(\x0b\x32\x16.pairing_server.Player\x12&\n\x06result\x18\x06 \x01(\x0e\x32\x16.pairing_server.Result*h\n\x06Result\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x44RAW\x10\x01\x12\r\n\tWHITE_WIN\x10\x02\x12\r\n\tBLACK_WIN\x10\x03\x12\x15\n\x11WHITE_FORFEIT_WIN\x10\x04\x12\x15\n\x11\x42LACK_FORFEIT_WIN\x10\x05\x62\x06proto3')
)

_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='pairing_server.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRAW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_WIN', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK_WIN', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WHITE_FORFEIT_WIN', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLACK_FORFEIT_WIN', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=634,
  serialized_end=738,
)
_sym_db.RegisterEnumDescriptor(_RESULT)

Result = enum_type_wrapper.EnumTypeWrapper(_RESULT)
NONE = 0
DRAW = 1
WHITE_WIN = 2
BLACK_WIN = 3
WHITE_FORFEIT_WIN = 4
BLACK_FORFEIT_WIN = 5



_HMAC = _descriptor.Descriptor(
  name='Hmac',
  full_name='pairing_server.Hmac',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='algorithm', full_name='pairing_server.Hmac.algorithm', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='digest', full_name='pairing_server.Hmac.digest', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=72,
)


_IDENTIFICATION = _descriptor.Descriptor(
  name='Identification',
  full_name='pairing_server.Identification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='pairing_server.Identification.uuid', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hmac', full_name='pairing_server.Identification.hmac', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=140,
)


_TOURNAMENT = _descriptor.Descriptor(
  name='Tournament',
  full_name='pairing_server.Tournament',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pairing_server.Tournament.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='pairing_server.Tournament.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rounds', full_name='pairing_server.Tournament.rounds', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=228,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='pairing_server.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pairing_server.Player.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='pairing_server.Player.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tournament', full_name='pairing_server.Player.tournament', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rating', full_name='pairing_server.Player.rating', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='withdrawn', full_name='pairing_server.Player.withdrawn', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expelled', full_name='pairing_server.Player.expelled', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=398,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='pairing_server.Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pairing_server.Game.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tournament', full_name='pairing_server.Game.tournament', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='round', full_name='pairing_server.Game.round', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='white', full_name='pairing_server.Game.white', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='black', full_name='pairing_server.Game.black', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='pairing_server.Game.result', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=632,
)

_IDENTIFICATION.fields_by_name['hmac'].message_type = _HMAC
_TOURNAMENT.fields_by_name['id'].message_type = _IDENTIFICATION
_PLAYER.fields_by_name['id'].message_type = _IDENTIFICATION
_PLAYER.fields_by_name['tournament'].message_type = _TOURNAMENT
_GAME.fields_by_name['id'].message_type = _IDENTIFICATION
_GAME.fields_by_name['tournament'].message_type = _TOURNAMENT
_GAME.fields_by_name['white'].message_type = _PLAYER
_GAME.fields_by_name['black'].message_type = _PLAYER
_GAME.fields_by_name['result'].enum_type = _RESULT
DESCRIPTOR.message_types_by_name['Hmac'] = _HMAC
DESCRIPTOR.message_types_by_name['Identification'] = _IDENTIFICATION
DESCRIPTOR.message_types_by_name['Tournament'] = _TOURNAMENT
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Game'] = _GAME
DESCRIPTOR.enum_types_by_name['Result'] = _RESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Hmac = _reflection.GeneratedProtocolMessageType('Hmac', (_message.Message,), dict(
  DESCRIPTOR = _HMAC,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Hmac)
  ))
_sym_db.RegisterMessage(Hmac)

Identification = _reflection.GeneratedProtocolMessageType('Identification', (_message.Message,), dict(
  DESCRIPTOR = _IDENTIFICATION,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Identification)
  ))
_sym_db.RegisterMessage(Identification)

Tournament = _reflection.GeneratedProtocolMessageType('Tournament', (_message.Message,), dict(
  DESCRIPTOR = _TOURNAMENT,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Tournament)
  ))
_sym_db.RegisterMessage(Tournament)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Player)
  ))
_sym_db.RegisterMessage(Player)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), dict(
  DESCRIPTOR = _GAME,
  __module__ = 'types_pb2'
  # @@protoc_insertion_point(class_scope:pairing_server.Game)
  ))
_sym_db.RegisterMessage(Game)


# @@protoc_insertion_point(module_scope)
